name: to_do
description: "To Do"
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State & Storage
  shared_preferences: ^2.2.2

  # Utilities
  intl: ^0.18.1

  # (Optional) Notifications — implement later if needed
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true